### ISSUE TITLE
Multiple controllers and cross-platform issue

### ISSUE THREAD

**Issue by oservieres** [daemon3000/InputManager#23]
This is a non-critical question. Mostly for curiosity.

This is my configuration : 

![image](https://cloud.githubusercontent.com/assets/2248284/19693233/11c1d562-9adb-11e6-954f-eec4364b8926.png)

My final purpose : make the game work with 4 controllers on Windows, Linux and Mac. Right now, the game works fine on Windows. It may also work correctly on other platforms with only one controller : the one defined in the Input Adapter. But I guess that the 3 other controllers are not gonna work.

At first I thought that I could use 4 input Adapters, each one assigned to a specific player, but it's a singleton.

So I'm quite stuck here.

**Comment by daemon3000** [comment]
My advice is to not use the Input Adapter at all, it's obsolete. Initially it was meant to solve the following issues:

1. Abstract away the fact that the XBox 360 controller has different buttons codes on each OS.
2. Allow you use use the DPAD and triggers as buttons instead of axes.

For point 1 it's much better to have a menu in your game where each player can rebind their buttons. Configure the game for the Windows XBox 360 drivers and let users on Mac and Linux rebind the buttons and axes. The added bonus with this solution is that the player can use any gamepad they want not just the XBox 360 one.

For point 2 you now have the **_Analog Button_** axis type which can convert any stick/trigger to button input.

If you don't want to allow the players to rebind the buttons you can also do it this way:

- Make three XBox 360 configurations, one for each OS, and set them up to receive input from **_Joystick 1_** for player **One**.
- Write a script that runs at the start of the game and does the following:
    - For each of the other three players, clone player **One**'s configurations and change the axis properties so it receives input from **_Joystick 2_**, **_Joystick 3_** and **_Joystick 4_**. Look at the **_CloneControllerConfiguration.cs_** script to get an idea on how to do it.
   - Check what platform you run on and assign the corresponding configuration to each player.

**Comment by oservieres** [comment]
Thank you very much for all these information ! I had the same kind of idea than you : declaring all the configurations possible for each player/platform and assigning the appropriate ones to the input manager based on the current platform.
But I didn't know that I could clone configuration. That may save a lot of time !

Thank you again.
