### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by SirFelolis** [daemon3000/InputManager#39]
It feels like this documentation is half-finished at best. Nothing works, and I keep getting complains about a gamepad adapter? Which I can't find anything about in the docs, or the examples.

Edit:
Seems like gamepad input is just broken. Too bad, this project seemed promising.

**Comment by daemon3000** [comment]
What Unity version are you using?

**Comment by ArceDeer** [comment]
Sorry to necro-bump this, but I feel like the OP wasn't being entirely specific. I believe he is talking about 'InputAdapter.cs', as well as every other instance that uses UnityEditor.InputManager . It seems on more recent versions of Unity (testing as of 2018.2) UnityEditor.InputManager has been made private, thus the errors.

`Assets/InputManager/Addons/InputAdapter/Runtime/InputAdapter.cs(152,12): error CS0122: UnityEditor.InputManager' is inaccessible due to its protection level`

**Comment by daemon3000** [comment]
I removed the InputAdapter addon last year so not sure how you're having issues with that. Just imported the project into Unity 2018.2.6 everything is fine. I'll test it more thoroughly this weekend.

Are you sure you have the latest version of the plugin?
