### ISSUE TITLE
No gamepad adapter has been assigned.

### ISSUE THREAD

**Issue by DragonZealot** [daemon3000/InputManager#46]
Im getting this error and cant seem to trace it. happens when calling a getaxis for a controller input

**Comment by daemon3000** [comment]
Add the **XInputDotNetAdapter** component on the **InputManager** game-object. This only works on Windows however. If you want the controller to work on other platforms as well change the input type from **GamepadButton(Axis)** to **Button** and **AnalogAxis** in your bindings. You'll most likely need a binding for each platform since the controller has different button codes on each platform(I'm assuming you're trying to use the XBox controller).
