### ISSUE TITLE
ArgumentException: Input Axis mouse_axis_0 is not setup

### ISSUE THREAD

**Issue by CraftedPvP** [daemon3000/InputManager#56]
I have a `LookHorizontal` and `LookVertical` for the mouse axis. however, it's not working and it's printing out this message. I'm not sure how to fix this. help pls?

![image](https://user-images.githubusercontent.com/20311462/77840863-5743af80-71be-11ea-9663-0d99ad6a94b1.png)

Code to call the Mouse Axis `InputManager.GetAxis("LookHorizontal")`

![image](https://user-images.githubusercontent.com/20311462/77840998-cec60e80-71bf-11ea-8b6d-d887754f7fcb.png)

I'll also note that whenever my scripts found on the 2nd image are enabled, my left click to the UI controls doesn't trigger an onClick event on buttons. I'm not sure why. but if it's disabled, it works fine

**Comment by CraftedPvP** [comment]
I found out that Unity's Input settings aren't being updated even if I click Overwrite in the Input Editor. I'm not sure how to go about this

**Comment by CraftedPvP** [comment]
I fixed the problem. It appears that hitting Overwrite in the Input Editor does nothing. I had to delete the Input manager game object in the hierarchy and then add another one through `Luminosity > Open Input Editor`. A dialog will pop saying you don't have an Input Manager. Click Create a new one. After clicking the button, the Input Manager found in the Project Settings will be updated.

In short, there's a bug in the Input Editor that comes with this in the `Overwrite` button. I'll close this once the issue has been resolved. For now, that's my temporary solution

**Comment by daemon3000** [comment]
After you select the **Override Project Settings** option you have to restart Unity or at least minimize/restore it because sometimes it won't detect the changes made to project settings files.

To make the UI work with this plugin you need to go to the **Luminosity** menu and select **Use Custom Input Module**. This will replace the **Standalone Input Module** component on **EventSystem** game-objects with a custom script. You need to do this in every scene where you have an **EventSystem** game-object.

You also need to create six buttons in the Input Editor for the UI: **UI_Up**, **UI_Down**, **UI_Left**, **UI_Right**, **UI_Submit** and **UI_Cancel**.

**Comment by CraftedPvP** [comment]
I tried minimizing or restarting Unity. It didn't work.. at least for me it didn't.

For the custom Standalone Input Module, I was able to attach that and set it accordingly like how you set it up in your Example 01's event system. Clicking isn't working. But UI with IPointerDownHandler interface works. The UI is working fine as long as the FirstPerson controller script is inactive but enabling it disables the UI to be clickable although it appears to be clickable. It's just not triggering the onclick function.

This is just a proof that I do have it set
![image](https://user-images.githubusercontent.com/20311462/77845270-1fe5fa80-71e0-11ea-9d05-c6d80b5b290a.png)

**Comment by daemon3000** [comment]
I was able to reproduce the **onClick** issue using this asset pack: https://assetstore.unity.com/packages/essentials/tutorial-projects/let-s-try-assets-66207

If the **First Person Controller** script is enabled it doesn't work but if I disable the script the **onClick** event fires. I'll let you know how to fix it once I figure it out.

**Comment by daemon3000** [comment]
I found the issue. It's related to the cursor lock, Unity doesn't allow locked cursors to interact with UI elements and by default the **MouseLook** script locks the cursor when you press the left mouse button which means the **onClick** event won't fire.

To fix it you have to edit the **MouseLook** script to check if the mouse cursor is over an UI element and if it is skip the cursor lock.

![](https://i.imgur.com/I4bcrqq.jpg)

I uploaded my test project on Google Drive. Download it and see if the issue is fixed for you too.
The test scene is in **Assets/Let's Try Shooter/Scenes/CompletedScenes**.
https://drive.google.com/file/d/1a62X7N0MMRS1eYDv-YsucbGC-qLCLRWd/view?usp=sharing

I also edited the **Ray Cast Shoot Complete** script to prevent firing when the mouse pointer is over an UI element.

![](https://i.imgur.com/xVclkvm.jpg)

**Comment by CraftedPvP** [comment]
yes! that's it! thank you. I seemed to have overlooked the `MouseLook.cs`.
